@startuml
left to right direction
skinparam packageStyle rectangle


actor "Comerciante" as C


rectangle "2.Calendario de Pedidos" {
  
  (Ver Calendario) as UC1
  (Vista detallada del pedido/servicio) as UC2
 }
  

C --> UC1
UC1 ..> UC2

@enduml