@startuml
left to right direction
skinparam packageStyle rectangle

actor "Comerciante" as M
actor "Cliente" as C

rectangle "2.Configuración de Reglas de Reserva" {
  
  (Gestionar Configuración de Producto) as UC_Config
  
  (Establecer Límite de Días) as UC_Establecer
  
  (Seleccionar Fecha de Recogida) as UC_Fecha
  
  (Validar Fecha Permitida) as UC_Validar
  (Mostrar Error 'Fecha no disponible') as UC_Error
}

M --> UC_Config

UC_Config <.. UC_Establecer : <<extend>>

C --> UC_Fecha

UC_Fecha ..> UC_Validar : <<include>>

UC_Validar <.. UC_Error : <<extend>>


@enduml