@startuml
left to right direction
skinparam packageStyle rectangle

actor "Comerciante" as M

rectangle "2. Gestión de Catálogo (CRUD)" {
  
  (Consultar Listado de Productos) as UC_Leer
(Crear Nuevo Producto) as UC_Crear
  (Editar Datos / Stock) as UC_Editar
  (Eliminar Producto) as UC_Eliminar
  
  (Confirmar Eliminación) as UC_Confirmar
}

M --> UC_Leer


UC_Leer <.. UC_Crear : <<extend>>
UC_Leer <.. UC_Editar : <<extend>>
UC_Leer <.. UC_Eliminar : <<extend>>

UC_Eliminar ..> UC_Confirmar : <<include>>

@enduml