@startuml
left to right direction
skinparam packageStyle rectangle

actor "Comerciante" as M
actor "Cliente" as C

rectangle "2. Productos Destacados" {
  
  (Gestionar Catálogo de Productos) as UC_Gestion
  (Marcar como 'Famoso' / 'Destacado') as UC_Marcar
  
  (Visualizar Perfil del Comercio) as UC_VerPerfil
  (Ver Sección 'Recomendados') as UC_VerDestacados
}

M --> UC_Gestion

UC_Gestion <.. UC_Marcar : <<extend>>


C --> UC_VerPerfil

UC_VerPerfil ..> UC_VerDestacados : <<include>>

@enduml