@startuml
left to right direction
skinparam packageStyle rectangle

actor "Cliente" as C
actor "API Maps" as MAPS

rectangle "3. Búsqueda y Geolocalización" {
  
  (Buscar Comercios Locales) as UC_Buscar
  
  (Filtrar por Categoría) as UC_Filtrar
  (Filtrar por Distancia) as UC_Dist
  
  (Visualizar Resultados en Mapa) as UC_VerMapa
  (Obtener Ubicación GPS) as UC_GPS
}

C --> UC_Buscar

UC_Buscar <.. UC_Filtrar : <<extend>>
UC_Buscar <.. UC_Dist : <<extend>>

UC_Buscar ..> UC_VerMapa : <<include>>

UC_VerMapa ..> UC_GPS : <<include>>

UC_VerMapa <-- MAPS : Renderizar mapa
UC_GPS --> MAPS : Solicitar coordenadas

@enduml